apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamfactory-api
  namespace: teamfactory
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      game: teamfactory
  template:
    metadata:
      namespace: teamfactory
      labels:
        app: api
        game: teamfactory
    spec:
      containers:
        - 
          name: teamfactory-api
          image: ghcr.io/devnull-twitch/teamfactory-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            -
              name: WEBSERVER_BIND
              value: ":8080"
            -
              name: EXTERNAL_IP
              value: "172.105.85.184"
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: teamfactory-api
  namespace: teamfactory
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
  selector:
    app: api
    game: teamfactory
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamfactory-ingress
  namespace: teamfactory
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - devnullga.me
      secretName: devnullgame-cert-secret
  rules:
    - host: devnullga.me
      http:
        paths:
          - path: /team_factory
            pathType: Prefix
            backend:
              service:
                name: teamfactory-api
                port:
                  number: 8080