apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamfactory-api
  namespace: teamfactory
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      game: teamfactory
  template:
    metadata:
      namespace: teamfactory
      labels:
        app: api
        game: teamfactory
    spec:
      containers:
        - 
          name: teamfactory-api
          image: ghcr.io/devnull-twitch/teamfactory-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            -
              name: WEBSERVER_BIND
              value: ":8080"
            -
              name: EXTERNAL_IP
              value: "172.105.85.184"
      imagePullSecrets:
        - name: dockerconfigjson-ghcr