on: 
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Write netrc file
        run: |
          printf "machine github.com\n" > netrc
          printf "login ${{ secrets.GHCR_USERNAME }}\n" >> netrc
          printf "password ${{ secrets.GHCR_TOKEN }}\n\n" >> netrc
          printf "machine api.github.com\n" > netrc
          printf "login ${{ secrets.GHCR_USERNAME }}\n" >> netrc
          printf "password ${{ secrets.GHCR_TOKEN }}\n" >> netrc
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.ref.name=${{ env.GIT_REF }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: ghcr.io/devnull-twitch/teamfactory-manager:latest